[package]
name = "gitprompt-rs"
description = "A very simple Git prompt"
version = "0.3.0"
authors = ["Dan Elkouby <streetwalkermc@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/Streetwalrus/gitprompt-rs"
edition = "2021"

[dependencies]
"lazy_static" = "1.4.0"
