[package]
name = "gitprompt-rs"
description = "A very simple Git prompt"
version = "0.4.0"
authors = ["novenary <novenary@kwak.zip>"]
license = "MPL-2.0"
repository = "https://github.com/9ary/gitprompt-rs"
edition = "2021"

[dependencies]
